# Generated by Django 4.0.4 on 2022-05-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teste',
            field=models.BooleanField(default=False),
        ),
    ]
