# Generated by Django 4.0.4 on 2022-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teste',
        ),
        migrations.AddField(
            model_name='customuser',
            name='costumer_status',
            field=models.BooleanField(default=False, verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_status',
            field=models.BooleanField(default=False, verbose_name='Gestor médico'),
        ),
    ]
