# Generated by Django 4.0.4 on 2022-05-24 00:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(choices=[('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h'), ('11h-12h', '13h-14h'), ('14h-15h', '15h-16h'), ('16h-17h', '17h-18h')], max_length=10, verbose_name='Horário')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do médico')),
                ('crm', models.CharField(help_text='Número do registro médico', max_length=10, unique=True, verbose_name='CRM do médico')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Medicals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=100, verbose_name='Nome da Especialidade')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.today, verbose_name='dia')),
                ('medical_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.medical', verbose_name='Médico')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.hour', verbose_name='Horário')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medical',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.specialty'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Data da Consulta')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('Espera', 'Espera'), ('Realizada', 'Realizada')], max_length=20, verbose_name='Status da Consulta')),
                ('disponible', models.BooleanField(default=True, verbose_name='Consulta Disponível')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.hour', verbose_name='Horário')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medical', verbose_name='Médico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.specialty', verbose_name='Especialidade da consulta')),
            ],
            options={
                'verbose_name_plural': 'Exams',
                'managed': True,
            },
        ),
    ]
