# Generated by Django 4.0.4 on 2022-05-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'managed': True, 'verbose_name_plural': 'hours'},
        ),
        migrations.AlterField(
            model_name='medical',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.specialty', verbose_name='Especialidade'),
        ),
    ]
