# Generated by Django 4.0.4 on 2022-05-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_hour_options_alter_medical_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='calendly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.schedule', verbose_name='Agenda médica'),
        ),
    ]
