# Generated by Django 4.0.4 on 2022-05-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_exam_calendly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'managed': True, 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='hour',
            options={'managed': True, 'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterModelOptions(
            name='medical',
            options={'managed': True, 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True, 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'managed': True, 'verbose_name': 'Especiaidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='calendly',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.schedule', verbose_name='Agenda médica'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
    ]
