# Generated by Django 4.0.4 on 2022-05-24 23:31

import clinica.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_exam_options_alter_hour_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='calendly',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='disponible',
        ),
        migrations.AddField(
            model_name='exam',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Consulta já foi realizada'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(default=datetime.datetime.today, validators=[clinica.models.Schedule.day_validator], verbose_name='dia'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('medical_name', 'day', 'schedule')},
        ),
    ]
