# Generated by Django 4.0.4 on 2022-05-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_rename_calendly_exam_schedule_remove_exam_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='day',
            field=models.DateField(null=True, verbose_name='Data da Consulta'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.hour', verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='medical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medical', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.specialty', verbose_name='Especialidade da consulta'),
        ),
    ]
