# Generated by Django 4.0.4 on 2022-05-30 02:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0006_alter_exam_day_alter_exam_hour_alter_exam_medical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='email',
            new_name='medical_email',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='name',
            new_name='medical_name',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='done',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='time_scheduled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='O valor máximo é de 14 dígitos', regex='^\\+?1?\\d{9,14}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='day',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='hour',
            field=models.CharField(choices=[('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h'), ('11h-12h', '13h-14h'), ('14h-15h', '15h-16h'), ('16h-17h', '17h-18h')], max_length=10, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.schedule', verbose_name='Agenda médica'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='medical_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.medical', verbose_name='Médico'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('medical_name', 'day')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule',
        ),
    ]
